name: beatboat
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.5+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.3
  cupertino_icons: ^1.0.2
  json_annotation: ^4.1.0
  dotted_border: ^2.0.0+1
  dio: ^5.0.0
  get: ^4.6.5
  intl: ^0.19.0
  flutter_svg: ^2.0.1
  shared_preferences: ^2.0.17
  package_info_plus: ^3.0.3
  share_files_and_screenshot_widgets: ^1.0.6
  fluttertoast: ^8.0.8
  cached_network_image: ^3.2.0
  url_launcher: ^6.1.5
  image_picker: ^0.8.4+4
  device_preview: ^1.1.0
  flutter_html: ^3.0.0-beta.1
  lazy_load_indexed_stack: ^0.1.4
  flutter_cupertino_date_picker_fork: ^1.0.7
  google_fonts: ^4.0.3
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^13.0.0
  flutter_cached_pdfview: ^0.4.1
  add_2_calendar: ^3.0.1
  #Permission
  permission_handler: ^10.2.0
  path_provider: ^2.0.13
  open_filex: ^4.3.2
  #UUID
  uuid: ^4.3.3
  #QR
  qr_code_scanner: ^1.0.1
  #deviceinfo
  device_info_plus: ^9.0.3
  jwt_decode: ^0.3.1
  connectivity_plus: ^5.0.2
  flutter_nfc_kit: ^3.4.2
  sqflite: ^2.3.2
  lottie: ^3.0.0
  flutter_udid: ^3.0.0
  sunmi_printer_plus: ^2.1.2
  flutter_esc_pos_network: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
  fonts:
    - family: Segoeui
      fonts:
        - asset: assets/fonts/segoeui/Segoeui-Regular.ttf
        - asset: assets/fonts/segoeui/Segoeui-Italic.ttf
          style: italic
        - asset: assets/fonts/segoeui/Segoeui-Bold.ttf
          weight: 700
        - asset: assets/fonts/segoeui/Segoeui-Bold-Italic.ttf
          weight: 700
          style: italic

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon_trans.png"
  image_path_ios: "assets/images/icon_trans.png"
  adaptive_icon_background: "#00FFFFFF"
  adaptive_icon_foreground: "assets/images/icon_trans.png"
